### ISSUE TITLE
BUG: USB-Sticks do not get unmounted during a hard power-off

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#62] opened 2021-06-24 13:17 UTC
We discovered a serious issue an (likely) all S-Series devices:
The device switches to constant blue lights and Mr Beam Plugin is not started. 
The folder ~/usb_mount still exists and contains the trigger file for the camera plugin. Therefore the device starts the camera plugin and does NOT start Mr Beam Plugin.

Immediate actions taken:
We created a dummy-usb stick which does almost nothing, but it replaces the trigger file in the ~/usb_mount folder. 

Needed Steps:
- Image needs to call `mount_manager clear` on during boot. This should happen before any potentially plugged in USB stick gets mounted
- Install this also on all S devices ALREADY SHIPPED. (Probably in a migration step)
- Test that with this change it is not possible that a device goes in calibration mode without a usb stick even if the device got hard powered off with the stick still plugged in.
- Make sure that ~/usb_mount folders never exists if no usb stick is plugged in (either after stick got unplugged or after a reboot.) Especially test with a stick wich reboots the device when unplugged. (Josef found an issue where the rebot happened before the mount_manager was able to remove this folder.)

**Comment by JFSolution** [comment] 2021-06-25 06:05
in legacy image it is done by /etc/rc.local
```
# clear mount_manager leftovers
/root/mount_manager/mount_manager clear
```

**Comment by JFSolution** [comment] 2021-06-25 07:09
https://github.com/mrbeam/BeamOS/commit/8869cb67b9832e424b746643a36f53cbeece42f9

**Comment by JFSolution** [comment] 2021-06-25 13:07
ask axel why he changed self.version_previous = self.plugin._settings.get(["version"]) or "0.0.0" in migration.py

**Comment by amrsoll** [comment] 2021-06-28 07:08
Hey all,

1. the plugin also looks for the `/media/` folder in case of a hard power off. If the usb stick is not in the device, there should Not be anything mounted in `/media/` - Therefore I think we should look at why there is still a leftover folder in `/media`
2. This is because we do not want to perform all the migration steps in `migration.py` the first time it start OctoPrint. All the problems those steps are mitigating should be fixed in the newest version of the image and software.
   > `self.version_previous = self.plugin._settings.get(["version"]) or "0.0.0"` in migration.py 
3. To further fix the problem, I would recommend that we copy all the sticks that are less than 5 MB onto a `tmpfs` which are automatically cleared on the following boot, and the other keys should be copied into `/tmp` which Also gets cleared on the following boot -> no need for time-sensitive `mount_manager clear`
   > Both the tmpfs and the folder in `/tmp` can be linked towards with a symlink to be backwards compatible : `~/usb_mount -> /tmp/mrb_usb`
4. For the devices that have been shipped, a migration in `migration.py` will not help because it will only work if MrBeamPlugin is running - which it is not. Therefore I think we should preemptively send some of our users a usb key with the correct migration file which triggers via `mount_manager`
5. Even if I understand that the expedience of the fix didn't allow for it yet, those kind of issues should be __documented__ in mount_manager so that we don't forget extra caution until the time where that gets fixed in the `mount_manager` project.
6. > the rebot happened before the mount_manager was able to remove this folder.

   If the folder needs to be removed during both startup and shutdown, then it is best to keep it as a systemd unit which will trigger both ways.

**Comment by JFSolution** [comment] 2021-06-28 07:47
it seems like the folders don't get removed by unmounting, the mount_manager removes these while clearing at boot
>the plugin also looks for the /media/ folder in case of a hard power off. If the usb stick is not in the device, there should Not be anything mounted in /media/ - Therefore I think we should look at why there is still a leftover folder in /media

But with the __version__ as fallback the migration will never trigger for devices without a migration yet, because it will always be the same.
> 2. This is because we do not want to perform all the migration steps in `migration.py` the first time it start OctoPrint. All the problems those steps are mitigating should be fixed in the newest version of the image and software.

As a hotfix I created a dummy stick for these devices, it does nothing. But it triggers the mount_manager and this deletes by unplugging all the folders, each other stick will help as well.
>For the devices that have been shipped, a migration in migration.py will not help because it will only work if MrBeamPlugin is running - which it is not. Therefore I think we should preemptively send some of our users a usb key with the correct migration file which triggers via mount_manager

**Comment by amrsoll** [comment] 2021-06-28 07:53
> it seems like the folders don't get removed by unmounting,

On a normal system, the folders get removed automatically by some other mechanism (probably `udev` now that I think about it) - unmounting does not remove folders onto which you mount a storage device. Therefore the problem is probably with the `udev` rules that have been overwritten.

> But with the version as fallback the migration will never trigger for devices without a migration yet, because it will always be the same.

That should be the exact expectation : No need for migration with newly installed software. The bug should be fixed outside of the migration step.

> As a hotfix I created a dummy stick for these devices, it does nothing. But it triggers the mount_manager and this deletes by unplugging all the folders, each other stick will help as well.

Yeah that is perfectly fine :)

**Closed as completed** 2021-06-28 08:27 UTC
Labels: bug
