### ISSUE TITLE
Device turns off on first boot

### ISSUE THREAD

**Issue by andywerner** [mrbeam/BeamOS#51] opened 2021-04-23 10:19 UTC
Last observed with DEV-2021-04-21 on Mr Beam DC (Raspi 3b)
In fact it went off two times now...

Not sure if it's only the first boot though.

**Comment by amrsoll** [comment] 2021-04-29 14:11
It doesn't seem to be a problem anymore, therefore closing the ticket for now

**Closed as completed by amrsoll** 2021-04-29 14:11 UTC
Labels: critical

**Comment by JFSolution** [comment] 2021-05-04 11:24
Some quick update, it is a timeout during the expansion of the file system, it could be reproduced with Andys 16Gb class 10 SD card.
It shuts down during the 5 second timer after the expansion.
Quick fix would be to cancel or shorten this timer, the better solution would be to activate the serial interface, so the MrBeamBoard don't switch the power off.

**Comment by amrsoll** [comment] 2021-05-04 11:52
Proposed Mitigations:
1. At assembly, the SD clone device clones a base SD card to other SD cards bit by bit -> Prepare an image with pre-epanded filesystem
  - Pro 
    - hacky and quick 
    - The Quickest 1st boot possible
  - Con 
    - Needs to be automated for every new image we roll out 
    - inflexible w/ regards to SD card size
2. Delete the timer for the filesystem expansion
  - Pro - hacky and quick + quicker 1st boot time
  - Con - Might not be enough + could fail at a later version
3. Activate the serial interface before fs expansion
  - Pro : 
    - Robust because we make sure the shield won't turn off the device
  - Con : 
    - Slowest 1st boot
    - Have to deal with systemd
